In [5]:
import numpy as np

In [6]:
# Numpy arrays are made up of a pointer to data, a data type (dtype), a shape, and strides.
# Strides are the distance it takes (in bytes) in any dimension to advance to the next element
arr_1d_int = np.zeros((5), dtype=np.int64)

In [7]:
arr_1d_int.dtype

dtype('int64')

In [8]:
arr_1d_int.shape

(5,)

In [9]:
# A 64 bit integer takes up 8 bytes - so the stride is 8.
arr_1d_int.strides

(8,)

In [10]:
arr_2d_int32 = np.zeros((4, 5), dtype=np.int32)

In [11]:
arr_2d_int32.dtype

dtype('int32')

In [12]:
arr_2d_int32.shape

(4, 5)

In [13]:
# A 32 bit integer takes up 4 bytes.
# In the second dimension, a stride is 4 because the next element in that dimension is only 4 bytes away.
# In the first dimension, a stride is 20 because the entire second dimension (of length 5 * 4 bytes) is traversed
# to reach the next element.
arr_2d_int32.strides

(20, 4)

In [14]:
np.int64.mro()

[numpy.int64,
 numpy.signedinteger,
 numpy.integer,
 numpy.number,
 numpy.generic,
 object]

In [15]:
np.uint8.mro()

[numpy.uint8,
 numpy.unsignedinteger,
 numpy.integer,
 numpy.number,
 numpy.generic,
 object]

In [16]:
np.float64.mro()

[numpy.float64,
 numpy.floating,
 numpy.inexact,
 numpy.number,
 numpy.generic,
 float,
 object]

In [17]:
np.string_.mro()

[numpy.bytes_, bytes, numpy.character, numpy.flexible, numpy.generic, object]

In [18]:
np.object_.mro()

[numpy.object_, numpy.generic, object]

In [19]:
np.issubdtype(np.int64, np.number)

True

In [20]:
np.issubdtype(np.int64, np.signedinteger)

True

In [21]:
np.issubdtype(np.uint16, np.signedinteger)

False

In [22]:
arr = np.arange(16)

In [23]:
# Reshaping arrays in numpy follows two different orderings - C and Fortran 
# (named after the respective programming languages).  By default reshape() uses C ordering, which is row major.
# This means the row is filled out one at a time.
arr.reshape((4, 4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [24]:
# C ordering (row major) can be explicitly specified.
arr.reshape((4, 4), order='C')

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [25]:
# Fortran ordering (column major) fills out columns one at a time.
arr.reshape((4, 4), order='F')

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In [36]:
arr = arr.reshape((4, 4))

In [37]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [39]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [40]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [41]:
arr.ravel('F')

array([ 0,  4,  8, 12,  1,  5,  9, 13,  2,  6, 10, 14,  3,  7, 11, 15])

In [33]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [48]:
arr1 = np.array([[1], [2]])
arr2 = np.array([[3], [4]])
np.concatenate((arr1, arr2))

array([[1],
       [2],
       [3],
       [4]])

In [49]:
np.concatenate((arr1, arr2), axis=0)

array([[1],
       [2],
       [3],
       [4]])

In [50]:
np.concatenate((arr1, arr2), axis=1)

array([[1, 3],
       [2, 4]])

In [52]:
# Equivalent to np.concatenate() on axis 0
np.vstack((arr1, arr2))

array([[1],
       [2],
       [3],
       [4]])

In [53]:
# Equivalent to np.concatenate() on axis 1
np.hstack((arr1, arr2))

array([[1, 3],
       [2, 4]])

In [55]:
arr = np.arange(10)
np.split(arr, [2, 4, 9])

[array([0, 1]), array([2, 3]), array([4, 5, 6, 7, 8]), array([9])]

In [61]:
arr = np.arange(3).repeat(2)
arr

array([0, 0, 1, 1, 2, 2])

In [57]:
np.array([5]).repeat(5)

array([5, 5, 5, 5, 5])

In [59]:
np.full([5], 5)

array([5, 5, 5, 5, 5])

In [65]:
np.tile(arr, (2, 1))

array([[0, 0, 1, 1, 2, 2],
       [0, 0, 1, 1, 2, 2]])

In [67]:
np.tile(arr, (1, 2))

array([[0, 0, 1, 1, 2, 2, 0, 0, 1, 1, 2, 2]])

In [71]:
arr1 = np.zeros((3, 3))
arr2 = np.array([1, 2, 3])
arr1[:] = arr2[:, np.newaxis]
arr1

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [72]:
np.add.reduce(np.arange(10))

45

In [74]:
# Logical AND chained with reduce() is equivalent to all()
arr = np.array([1, 1])
np.logical_and.reduce(arr == 1)

True

In [75]:
arr = np.arange(16).reshape((4, 4))
np.add.accumulate(arr, axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21],
       [24, 28, 32, 36]])

In [76]:
np.add.accumulate(arr, axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38],
       [12, 25, 39, 54]])