In [2]:
import numpy as np

In [4]:
# Creates a numpy array containing five values.  The values are randomly generated with mean 0 and variance 1.
# Basically floating-point numbers close to zero.
# https://www.mathsisfun.com/data/standard-deviation.html
# Source: https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.random.randn.html
random_array = np.random.randn(5)

In [6]:
random_array

array([ 0.38165718,  0.43274056,  0.18617809,  1.36847893, -1.53137334])

In [7]:
# numpy arrays can be multi-dimensional
md_rand_array = np.random.randn(4, 3)
md_rand_array

array([[ 1.91702264,  0.09822134,  0.70506034],
       [-1.6811057 ,  0.84311188,  0.0564485 ],
       [ 1.05707155, -1.09465172,  0.03756885],
       [ 1.2214609 ,  1.52124806, -0.06572644]])

In [8]:
md_rand_array.size

12

In [9]:
md_rand_array.shape

(4, 3)

In [10]:
# Create an array of ten integers ranging from 0 to 9.
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
# Perform vectoriztion on the array.  In numpy, this is when a looping operation on an array
# is conducted without an actual for loop.
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
arr / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [13]:
arr % 3

array([0, 1, 2, 0, 1, 2, 0, 1, 2, 0])

In [14]:
# Vectorization operations create a new view of the array - they don't alter the original array.
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
arr == [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [19]:
(arr == [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]).all()

True

In [20]:
(arr == [0, 1, 2, 3, 4, 5, 6, 6, 8, 9]).all()

False

In [23]:
# Demonstrate the speed increase of using numpy arrays over built-in Python arrays
%time for _ in range(1000): np.arange(100) * 2

CPU times: user 3.14 ms, sys: 2.72 ms, total: 5.87 ms
Wall time: 5.43 ms


In [24]:
%time for _ in range(1000): [item * 2 for item in np.arange(100)]

CPU times: user 44 ms, sys: 5.7 ms, total: 49.7 ms
Wall time: 45.8 ms


In [28]:
# Using the standard numpy array constructor
arr = np.array(['watched', 'frozen', 'broadway', 'with', 'fam', ',', 'race', 'in', 'a', 'bit'])
arr

array(['watched', 'frozen', 'broadway', 'with', 'fam', ',', 'race', 'in',
       'a', 'bit'], dtype='<U8')