In [1]:
import numpy as np

In [15]:
# Numpy arrays are made up of a pointer to data, a data type (dtype), a shape, and strides.
# Strides are the distance it takes (in bytes) in any dimension to advance to the next element
arr_1d_int = np.zeros((5), dtype=np.int64)

In [16]:
arr_1d_int.dtype

dtype('int64')

In [17]:
arr_1d_int.shape

(5,)

In [18]:
# A 64 bit integer takes up 8 bytes - so the stride is 8.
arr_1d_int.strides

(8,)

In [19]:
arr_2d_int32 = np.zeros((4, 5), dtype=np.int32)

In [20]:
arr_2d_int32.dtype

dtype('int32')

In [21]:
arr_2d_int32.shape

(4, 5)

In [22]:
# A 32 bit integer takes up 4 bytes.
# In the second dimension, a stride is 4 because the next element in that dimension is only 4 bytes away.
# In the first dimension, a stride is 20 because the entire second dimension (of length 5 * 4 bytes) is traversed
# to reach the next element.
arr_2d_int32.strides

(20, 4)

In [24]:
np.int64.mro()

[numpy.int64,
 numpy.signedinteger,
 numpy.integer,
 numpy.number,
 numpy.generic,
 object]

In [25]:
np.uint8.mro()

[numpy.uint8,
 numpy.unsignedinteger,
 numpy.integer,
 numpy.number,
 numpy.generic,
 object]

In [26]:
np.float64.mro()

[numpy.float64,
 numpy.floating,
 numpy.inexact,
 numpy.number,
 numpy.generic,
 float,
 object]

In [27]:
np.string_.mro()

[numpy.bytes_, bytes, numpy.character, numpy.flexible, numpy.generic, object]

In [32]:
np.object_.mro()

[numpy.object_, numpy.generic, object]

In [29]:
np.issubdtype(np.int64, np.number)

True

In [30]:
np.issubdtype(np.int64, np.signedinteger)

True

In [31]:
np.issubdtype(np.uint16, np.signedinteger)

False

In [34]:
arr = np.arange(16)

In [35]:
# Reshaping arrays in numpy follows two different orderings - C and Fortran 
# (named after the respective programming languages).  By default reshape() uses C ordering, which is row major.
# This means the row is filled out one at a time.
arr.reshape((4, 4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [36]:
# C ordering (row major) can be explicitly specified.
arr.reshape((4, 4), order='C')

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [37]:
# Fortran ordering (column major) fills out columns one at a time.
arr.reshape((4, 4), order='F')

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])