In [8]:
import numpy as np

In [9]:
# Creates a numpy array containing five values.  The values are randomly generated with mean 0 and variance 1.
# Basically floating-point numbers close to zero.
# https://www.mathsisfun.com/data/standard-deviation.html
# Source: https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.random.randn.html
random_array = np.random.randn(5)

In [10]:
random_array

array([ 0.01646453,  0.11655652,  0.63362623,  0.99452094, -0.11363738])

In [11]:
# numpy arrays can be multi-dimensional
md_rand_array = np.random.randn(4, 3)
md_rand_array

array([[-0.52987859,  1.58117759,  0.33713899],
       [-1.14327818,  1.06131866, -0.62628385],
       [-0.68584681,  0.40478916, -2.81961703],
       [-0.08116553, -0.51175509,  1.67457195]])

In [12]:
md_rand_array.size

12

In [13]:
md_rand_array.shape

(4, 3)

In [14]:
# Create an array of ten integers ranging from 0 to 9.
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
# Perform vectoriztion on the array.  In numpy, this is when a looping operation on an array
# is conducted without an actual for loop.
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [16]:
native_arr = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

def mult_by_2(arr: list, val: int) -> list:
    new_arr = arr.copy()
    
    for i in range(len(new_arr)):
        new_arr[i] *= val
        
    return new_arr
    
mult_by_2(native_arr, 2)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [17]:
arr / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [18]:
arr % 3

array([0, 1, 2, 0, 1, 2, 0, 1, 2, 0])

In [19]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [23]:
def mult_together(arr1: list, arr2: list) -> list:
    return [arr1[i] * arr2[i] for i in range(len(arr1))]

mult_together(native_arr, native_arr)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [20]:
# Vectorization operations create a new view of the array - they don't alter the original array.
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
arr == [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [19]:
(arr == [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]).all()

True

In [20]:
(arr == [0, 1, 2, 3, 4, 5, 6, 6, 8, 9]).all()

False

In [23]:
# Demonstrate the speed increase of using numpy arrays over built-in Python arrays
%time for _ in range(1000): np.arange(100) * 2

CPU times: user 3.14 ms, sys: 2.72 ms, total: 5.87 ms
Wall time: 5.43 ms


In [24]:
%time for _ in range(1000): [item * 2 for item in np.arange(100)]

CPU times: user 44 ms, sys: 5.7 ms, total: 49.7 ms
Wall time: 45.8 ms


In [28]:
# Using the standard numpy array constructor
arr = np.array(['watched', 'frozen', 'broadway', 'with', 'fam', ',', 'race', 'in', 'a', 'bit'])
arr

array(['watched', 'frozen', 'broadway', 'with', 'fam', ',', 'race', 'in',
       'a', 'bit'], dtype='<U8')

In [29]:
# You can check the data type of numpy arrays with dtype
arr = np.array([1, 2, 3])
arr.dtype

dtype('int64')

In [51]:
# Multi-dimensional arrays can also be created with array()
arr = np.array([[0, 0.5, 1, 1.5], [2, 2.5, 3, 3.5]])

In [52]:
arr.shape

(2, 4)

In [53]:
arr.dtype

dtype('float64')

In [54]:
arr.ndim

2

In [56]:
np.zeros(3)

array([0., 0., 0.])

In [57]:
# Empty creates an array without initializing values.  Its content may just be garbage values.
np.empty((2, 2))

array([[4.9e-324, 9.9e-324],
       [9.9e-324, 1.5e-323]])

In [58]:
# 3D array
np.zeros((2, 2, 2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [59]:
np.ones(3)

array([1., 1., 1.])

In [61]:
np.full((2, 3), 4)

array([[4, 4, 4],
       [4, 4, 4]])

In [63]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [65]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [67]:
arr = np.array([2, 3])

In [69]:
arr.dtype

dtype('int64')

In [73]:
arr = arr.astype(np.int32)

In [74]:
arr.dtype

dtype('int32')

In [75]:
arr = arr.astype('i2')

In [76]:
arr.dtype

dtype('int16')

In [79]:
# Typical Python indexing...
arr = np.arange(10)
arr[1]

1

In [81]:
# ...and slicing is available for numpy arrays
arr[1:4]

array([1, 2, 3])

In [83]:
# Change all values in the array
arr[:] = 2
arr

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [85]:
arr = np.arange(10)
arr2 = arr[:]
arr2[:] = 2
arr

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [86]:
# Without explicitly invoking copy(), slices return views (references) of the original array
arr = np.arange(10)
arr2 = arr[:].copy()
arr2[:] = 2
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [94]:
# Unlike Python arrays, slices accept comma separated values.  Each value is a slice for a dimension of the array
arr_2d = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr_2d[1, 1]

4

In [95]:
arr_2d[:, :]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [97]:
arr_2d[1:, :1]

array([[3],
       [6]])

In [100]:
arr_2d[:, 2]

array([2, 5, 8])

In [101]:
arr_2d[:, 2:]

array([[2],
       [5],
       [8]])

In [102]:
arr_2d[:, 2] = 10
arr_2d

array([[ 0,  1, 10],
       [ 3,  4, 10],
       [ 6,  7, 10]])

In [105]:
arr_2d[2, arr_2d[2] == 6]

array([6])

In [110]:
arr_2d[1, arr_2d[1] > 3]

array([ 4, 10])

In [111]:
arr_2d[arr_2d > 3]

array([10,  4, 10,  6,  7, 10])

In [113]:
arr_2d[~(arr_2d > 5)]

array([0, 1, 3, 4])

In [114]:
arr_2d[(arr_2d < 2) | (arr_2d > 8)]

array([ 0,  1, 10, 10, 10])

In [115]:
arr_2d[(arr_2d > 2) & (arr_2d < 8)]

array([3, 4, 6, 7])

In [116]:
arr_2d[(arr_2d > 3) & (arr_2d < 7)] = 20
arr_2d

array([[ 0,  1, 10],
       [ 3, 20, 10],
       [20,  7, 10]])

In [118]:
arr_2d = np.array([[11, 12, 13], [21, 22, 23], [31, 32, 33], [41, 42, 43]])
arr_2d

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33],
       [41, 42, 43]])

In [120]:
# Fancy indexing in numpy is when indexing is performed with an integer array.
arr_2d[[0, 2]]

array([[11, 12, 13],
       [31, 32, 33]])

In [122]:
arr_2d[[-4, -2]]

array([[11, 12, 13],
       [31, 32, 33]])

In [124]:
arr_3d = np.arange(18).reshape(2, 3, 3)
arr_3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [125]:
arr_3d[[1]]

array([[[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [129]:
arr_3d[[0, 1], [1, 1]]

array([[ 3,  4,  5],
       [12, 13, 14]])

In [133]:
# Rearrange the axis.  The original shape was (X, Y, Z).  The resulting shape is (Z, X, Y)
arr_3d.transpose((2, 0, 1))

array([[[ 0,  3,  6],
        [ 9, 12, 15]],

       [[ 1,  4,  7],
        [10, 13, 16]],

       [[ 2,  5,  8],
        [11, 14, 17]]])

In [131]:
# arange() works just like Python's range()
arr_2d = np.arange(12, 36, 2).reshape(3, 4)
arr_2d

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [132]:
arr_2d.T

array([[12, 20, 28],
       [14, 22, 30],
       [16, 24, 32],
       [18, 26, 34]])